export const INITIAL_EMPLOYEES = [
  { id: 'EMP-01', name: 'Syauqi Iwan', role: 'Kasir & Barista', phone: '0812-3456-7890', pin: '1234' },
  { id: 'EMP-02', name: 'Siti Rahma', role: 'Kasir & Kitchen', phone: '0813-9876-5432', pin: '1111' },
  { id: 'EMP-03', name: 'Andi Pratama', role: 'Supervisor & Kasir', phone: '0857-1122-3344', pin: '2222' },
];

export const INITIAL_CATEGORIES = ['Semua', 'Makanan', 'Minuman', 'Snack', 'Paket'];

export const INITIAL_PRODUCTS = [
  {
    id: 'PRD-01',
    name: 'Kopi Susu Gula Aren',
    category: 'Minuman',
    price: 18000,
    cost: 8000,
    stock: 50,
    isAvailable: true,
    icon: 'coffee',
    description: 'Espresso blend pilihan dengan susu segar dan gula aren asli',
  },
  {
    id: 'PRD-02',
    name: 'Matcha Latte Ice',
    category: 'Minuman',
    price: 22000,
    cost: 10000,
    stock: 35,
    isAvailable: true,
    icon: 'glass-water',
    description: 'Matcha Uji premium dipadukan susu creamy',
  },
  {
    id: 'PRD-03',
    name: 'Americano Double Shot',
    category: 'Minuman',
    price: 15000,
    cost: 5000,
    stock: 40,
    isAvailable: true,
    icon: 'coffee',
    description: 'Espresso murni 100% Arabika dengan air mineral dingin',
  },
  {
    id: 'PRD-04',
    name: 'Nasi Goreng Spesial',
    category: 'Makanan',
    price: 25000,
    cost: 12000,
    stock: 25,
    isAvailable: true,
    icon: 'utensils',
    description: 'Nasi goreng bumbu rempah dengan telur, ayam suwir & kerupuk',
  },
  {
    id: 'PRD-05',
    name: 'Mie Goreng Seafood',
    category: 'Makanan',
    price: 28000,
    cost: 14000,
    stock: 20,
    isAvailable: true,
    icon: 'utensils',
    description: 'Mie telur kenyal dengan topping udang, cumi, dan bakso ikan',
  },
  {
    id: 'PRD-06',
    name: 'Ayam Geprek Sambal Bawang',
    category: 'Makanan',
    price: 23000,
    cost: 11000,
    stock: 30,
    isAvailable: true,
    icon: 'drumstick-bite',
    description: 'Ayam krispi gurih dengan ulekan sambal bawang pedas nampol',
  },
  {
    id: 'PRD-07',
    name: 'Kentang Goreng Keju',
    category: 'Snack',
    price: 16000,
    cost: 7000,
    stock: 40,
    isAvailable: true,
    icon: 'cookie',
    description: 'French fries renyah dengan taburan keju gurih & saus mayo',
  },
  {
    id: 'PRD-08',
    name: 'Roti Bakar Cokelat Keju',
    category: 'Snack',
    price: 18000,
    cost: 8000,
    stock: 15,
    isAvailable: true,
    icon: 'bread-slice',
    description: 'Roti tebal panggang dengan keju cheddar melimpah & mesis',
  },
  {
    id: 'PRD-09',
    name: 'Paket Hemat Nongkrong',
    category: 'Paket',
    price: 32000,
    cost: 15000,
    stock: 20,
    isAvailable: true,
    icon: 'box-open',
    description: '1 Kopi Susu Gula Aren + 1 Porsi Kentang Goreng Keju',
  },
];

export const INITIAL_STORE_INFO = {
  name: 'radiz gaming',
  tagline: 'Modern POS, Presensi & Shift',
  address: 'Jl. Kampus Merdeka No. 45, Gedung Fasilkom',
  phone: '0812-9988-7766',
  footerMessage: 'Terima kasih atas kunjungan Anda!\nBarang yang sudah dibeli tidak dapat ditukar.',
};
